version: "3.8"

services:
  db:
    image: mongo:6.0-rc-nanoserver-1809
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - db_net
  web:
    build:
      context: ./inaj-web
      dockerfile: Dockerfile
    depends_on:
      - backend
    container_name: web
    ports:
      - "3000:3000"
    networks:
      - app_net
  backend:
    build:
      context: ./inaj-back
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    container_name: back
    networks:
      - app_net
      - db_net

networks:
  app_net:
    driver: bridge
  db_net:
    driver: bridge