spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: inaj
      username: dumij
      password: dumij
      authentication-database: admin
  freemarker:
    check-template-location: false